### ISSUE TITLE
Use of tf2jax Operators?

### ISSUE THREAD

**Issue by adam-hartshorne** [aterenin/SparseGPAX#2]
It not really an issue, its more a question. I notice in the code that you make wide use of the following tf2jax operations in order to utilise tensorflow operators e.g.

tf2jax.linalg.LinearOperatorLowerTriangular(cholesky).solvevec(tf2jax.linalg.LinearOperatorLowerTriangular(cholesky).solvevec(residual), adjoint=True)

Is there a particular reason e.g speed, why one would want to do this over just using the native jax equivalent operators?

**Comment by aterenin** [comment]
The reason for this is because at the time, JAX did not natively support batched triangular solves. I believe this is now supported.

This package is at this point deprecated in favor of GPJax - I'm meeting with the authors of that package next week to describe how to roll in this package's functionality into there.

**Comment by adam-hartshorne** [comment]
Thanks for the quick response. I look forward to the inclusion of your pathwise sampling approach into GPJax.
